#!/system/bin/sh
# quick and dirty (how I like 'em) dalvik cache to /cache script
# kudos to cyanogen for the idea
# by paul@modaco.com

rm /data/dalvik-cache
mkdir /data/dalvik-cache
mkdir /cache/dalvik-cache

cd /cache/dalvik-cache

for filename in data*
do
	if [ ! -L $filename ]
        then
		mv $filename /data/dalvik-cache/$filename	
        fi
done;

for filename in system*
do
	if [ ! -L $filename ]
	then
        	ln -s /cache/dalvik-cache/$filename /data/dalvik-cache/$filename
	fi
done;

cd /data/dalvik-cache

for filename in system*
do
	if [ ! -L $filename ]
        then
		mv $filename /cache/dalvik-cache/$filename
		ln -s /cache/dalvik-cache/$filename /data/dalvik-cache/$filename
	fi
done;
